const domainData = [
  {
    id: "item-1",
    name: "businnesservices.space",
    priceLari: 320,
    priceDollar: "14,285.7",
    category: "business",
  },
  {
    id: "item-2",
    name: "realestate.edu.ge",
    priceLari: 540,
    priceDollar: "17,857.1",
    category: "realestate",
  },
  {
    id: "item-3",
    name: "myauto.com.ge",
    priceLari: 980,
    priceDollar: "17,857.1",
    category: "auto",
  },
  {
    id: "item-4",
    name: "medicsales.com",
    priceLari: 50,
    priceDollar: "17,857.1",
    category: "medic",
  },
  {
    id: "item-5",
    name: "marketer.com",
    priceLari: 1250,
    priceDollar: "17,857.1",
    category: "technology",
  },
  {
    id: "item-6",
    name: "gijashvili.ptv.com",
    priceLari: 940,
    priceDollar: "17,857.1",
    category: "games",
  },
  {
    id: "item-7",
    name: "domenebi.com",
    priceLari: 750,
    priceDollar: "17,857.1",
    category: "chillandhavefun",
  },
  {
    id: "item-8",
    name: "gijashvili.space",
    priceLari: 650,
    priceDollar: "17,857.1",
    category: "media",
  },
  {
    id: "item-9",
    name: "gijashvili.net",
    priceLari: 520,
    priceDollar: "17,857.1",
    category: "education",
  },
  {
    id: "item-10",
    name: "gijashvili.com.ge",
    priceLari: 420,
    priceDollar: "17,857.1",
    category: "commerce",
  },
  {
    id: "item-11",
    name: "gijashvili.edu.ge",
    priceLari: 888,
    priceDollar: "17,857.1",
    category: "finance",
  },
  {
    id: "item-12",
    name: "zoomer.net.ge",
    priceLari: 970,
    priceDollar: "17,857.1",
    category: "business",
  },
];

export default domainData;

export const categoryMapping = {
  business: "ბიზნესი",
  realestate: "უძრავი ქონება",
  auto: "ავტო",
  medic: "მედიცინა",
  technology: "ტექნოლოგიები",
  games: "თამაშები",
  chillandhavefun: "გართობა და დასვენება",
  media: "მედია",
  education: "განათლება",
  commerce: "კომერცია",
  finance: "ფინანსები",
};
